version: "3.6"
services:
  postgres:
    image: postgres:15
    ports:
      - "5838:5432" # expose pg on port 5832 to not collide with pg from elswhere
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  sync:
    build:
      context: .
    environment:
      VERCEL_URL: "https://t3-fissa-nextjs.vercel.app"

volumes:
  db_data:
