/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FissaCreateRouteImport } from './routes/fissa/create'
import { Route as FissaPinRouteImport } from './routes/fissa/$pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FissaCreateRoute = FissaCreateRouteImport.update({
  id: '/fissa/create',
  path: '/fissa/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FissaPinRoute = FissaPinRouteImport.update({
  id: '/fissa/$pin',
  path: '/fissa/$pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fissa/$pin': typeof FissaPinRoute
  '/fissa/create': typeof FissaCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fissa/$pin': typeof FissaPinRoute
  '/fissa/create': typeof FissaCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fissa/$pin': typeof FissaPinRoute
  '/fissa/create': typeof FissaCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fissa/$pin' | '/fissa/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fissa/$pin' | '/fissa/create'
  id: '__root__' | '/' | '/fissa/$pin' | '/fissa/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FissaPinRoute: typeof FissaPinRoute
  FissaCreateRoute: typeof FissaCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fissa/create': {
      id: '/fissa/create'
      path: '/fissa/create'
      fullPath: '/fissa/create'
      preLoaderRoute: typeof FissaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fissa/$pin': {
      id: '/fissa/$pin'
      path: '/fissa/$pin'
      fullPath: '/fissa/$pin'
      preLoaderRoute: typeof FissaPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FissaPinRoute: FissaPinRoute,
  FissaCreateRoute: FissaCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
