import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import * as schema from "./schema";

export * from "./schema";
export type { InferSelectModel } from "drizzle-orm";

import type { InferSelectModel } from "drizzle-orm";
import { type fissas, type tracks } from "./schema";
export type Fissa = InferSelectModel<typeof fissas>;
export type Track = InferSelectModel<typeof tracks>;

import { env } from "@fissa/env";

const client = postgres(env.DATABASE_URL);

const createDb = () => drizzle(client, { schema });

type DrizzleDB = ReturnType<typeof createDb>;

const globalForDb = globalThis as unknown as { db: DrizzleDB };

export const db: DrizzleDB = globalForDb.db ?? createDb();

if (env.NODE_ENV !== "production") globalForDb.db = db;

export type DB = DrizzleDB;

/**
 * Run all pending Drizzle migrations.
 * `migrationsFolder` must point to the directory containing the SQL files
 * generated by `drizzle-kit generate`.
 *
 * If the database was previously set up via `db:push` (tables exist but no
 * migration history), we seed the journal so migrations aren't re-applied.
 */
export async function runMigrations(migrationsFolder: string) {
  // Check if the DB was bootstrapped via db:push (tables exist, no migration records)
  const hasTable = await client`
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'fissas'
    LIMIT 1
  `;
  const hasMigrations = await client`
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'drizzle' AND table_name = '__drizzle_migrations'
    LIMIT 1
  `;
  const migrationCount = hasMigrations.length
    ? await client`SELECT count(*)::int AS c FROM drizzle.__drizzle_migrations`
    : [{ c: 0 }];

  if (hasTable.length > 0 && (migrationCount[0]?.c ?? 0) === 0) {
    // Tables exist but no migrations recorded — seed the initial migration
    console.info("[migrations] detected db:push state, seeding migration journal");
    await client`
      CREATE SCHEMA IF NOT EXISTS drizzle
    `;
    await client`
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
        id serial PRIMARY KEY,
        hash text NOT NULL,
        created_at bigint
      )
    `;
    // Read the journal to get the hash drizzle expects
    const fs = await import("node:fs");
    const nodePath = await import("node:path");
    const journal = JSON.parse(
      fs.readFileSync(nodePath.join(migrationsFolder, "meta", "_journal.json"), "utf-8"),
    ) as { entries: Array<{ tag: string; when: number }> };
    for (const entry of journal.entries) {
      const sqlContent = fs.readFileSync(
        nodePath.join(migrationsFolder, `${entry.tag}.sql`),
        "utf-8",
      );
      const hash = await cryptoHash(sqlContent);
      await client`
        INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
        VALUES (${hash}, ${String(entry.when)})
      `;
    }
    console.info("[migrations] journal seeded");
  }

  await migrate(db, { migrationsFolder });
}

async function cryptoHash(content: string): Promise<string> {
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(content).digest("hex");
}
